const data = [
  // pizza:
  [
    {
      mainimg: "pizzaMain1.png",
      mainid: "1",
      mainname: "Pizza",
      maindesc: "lorem ipsum blah",
      id: [0,0],
      name: "Chicken Pizza",
      count:0, desc:"",
      rating: "",
      price: 149,
      img: "pizza1.png",
      order: 0,
    },
    {
      id: [0,1],
      name: "Paneer Pizza",
      count:0, desc:"",
      rating: "",
      price: 249,
      img: "pizza2.png",
      order: 0,
    },
    {
      id: [0,2],
      name: "Tamato Pizza",
      count:0, desc:"",
      rating: "",
      price: 299,
      img: "pizza3.png",
      order: 0,
    },
    {
      id: [0,3],
      name: "Corn Pizza",
      count:0, desc:"",
      rating: "",
      price: 399,
      img: "pizza4.png",
      order: 0,
    },
    
    
  ],
  // burger:
  [
    {
      mainimg: "burger1.png",
      mainid: "2",
      mainname: "Burger",
      maindesc: "lorem ipsum blah",
      id: [1,0],
      name: "Chicken Burger",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "burger1.png",
      order: 0,
    },
    {
      id: [1,1],
      name: "Veg Burger",
      count:0, desc:"",
      rating: "",
      price: 99,
      img: "burger2.png",
      order: 0,
    },
    {
      id: [1,2],
      name: "Combo",
      count:0, desc:"",
      rating: "",
      price: 129,
      img: "burger3.png",
      order: 0,
    },
    {
      id: [1,3],
      name: "Cheese Burger",
      count:0, desc:"",
      rating: "",
      price: 149,
      img: "burger4.png",
      order: 0,
    },
  ],
  // snacks:
  [
    {
      mainimg: "snacksMain1.png",
      mainid: "3",
      mainname: "Snacks",
      maindesc: "lorem ipsum blah",
      id: [2,0],
      name: "French Fries",
      count:0, desc:"",
      rating: "",
      price: 59,
      img: "snacks1.png",
      order: 0,
    },
    {
      id: [2,1],
      name: "Chicken Nuggets",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "snacks2.png",
      order: 0,
    },
    {
      id: [2,2],
      name: "Samosa",
      count:0, desc:"",
      rating: "",
      price: 29,
      img: "snacks3.png",
      order: 0,
    },
    {
      id: [2,3],
      name: "Shawarma",
      count:0, desc:"",
      rating: "",
      price: 129,
      img: "snacks4.png",
      order: 0,
    },
  ],
  // drinks:
  [
    {
      mainimg: "drink1.png",
      mainid: "4",
      mainname: "Drinks",
      maindesc: "lorem ipsum blah",
      id: [],
      name: "StrawBerry",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "drink1.png",
      order: 0,
    },
    {
      id: "42",
      name: "Mango",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "drink2.png",
      order: 0,
    },
    {
      id: "43",
      name: "WaterMelon",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "drink3.png",
      order: 0,
    },
    {
      id: "44",
      name: "CockTail",
      count:0, desc:"",
      rating: "",
      price: 79,
      img: "drink4.png",
      order: 0,
    },
  ],
];

export default data;
